Traceback (most recent call last):
  File "c:\users\hanlu\anaconda3\lib\site-packages\nbclient\client.py", line 609, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "c:\users\hanlu\anaconda3\lib\site-packages\nbclient\util.py", line 85, in ensure_async
    result = await obj
  File "c:\users\hanlu\anaconda3\lib\site-packages\jupyter_client\asynchronous\channels.py", line 48, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hanlu\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\hanlu\anaconda3\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\hanlu\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\hanlu\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\hanlu\anaconda3\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "c:\users\hanlu\anaconda3\lib\site-packages\nbclient\client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\hanlu\anaconda3\lib\site-packages\nbclient\client.py", line 816, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "c:\users\hanlu\anaconda3\lib\site-packages\nbclient\client.py", line 633, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "c:\users\hanlu\anaconda3\lib\site-packages\nbclient\client.py", line 684, in _async_handle_timeout
    "Cell execution timed out", timeout, cell
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
["business_review_df = pd.merge(business_df, review_df, on='business_id', how='outer')", '# Function to test if something is an adjective', "is_adj = (lambda pos: pos[:2] == 'JJ')", '', '# Function for tokenizing the text into a list of words']
...
['n = 10', 'business_top_keywords = retrieve_top_n_keywords(n)', '', '# Add a column containing top keywords of each business to the original dataframe', "business_df['top_keywords'] = business_df['business_id'].map(business_top_keywords)"]
-------------------

